<?php
include ("../ls/livesearch.class.php");
  $LiveSearch = new LiveSearch();
  $add2style = "code,pre {display:block;color:#088A08;margin:10px;overflow:auto;}
      h4 {margin: 15px 0;}
      .table.table-width-auto {width:auto;}
      .text-right,td.text-right {text-align: right}";
  $thisPage = "Argumentos da Inexistência de Deus";
  include("../includes/header.php"); 
  
?>
<!DOCTYPE html>
<html>
<body>
 <script type="text/javascript" src="../js/jquery.min.js"></script>
 <script type="text/javascript" src="../js/jquery.maphilight.min.js"></script>
   <link rel="stylesheet" href="../css/bootstrap.min.css" type="text/css" />
    <link rel="stylesheet" href="../css/bootstrap-responsive.min.css" type="text/css" />
    <link rel="stylesheet" href="../ls/livesearch.css" type="text/css" />

    <script type="text/javascript" src="../js/jquery.1.9.1.min.js"></script>
    <script type="text/javascript" src="../js/bootstrap.min.js"></script>
<link rel="stylesheet" href="../assets/plugins/font-awesome/css/font-awesome.css">
    <link rel="stylesheet" href="../assets/plugins/elegant_font/css/style.css">
 <link id="theme-style" rel="stylesheet" href="../assets/css/styles.css">
<p><b>Dez argumentos a favor da inexistência
</b></p>
<hr>
</p><p>

<blockquote>
<p>“A existência em Deus implica necessariamente a escravidão de tudo abaixo dele. Assim se Deus existisse, só haveria um meio de servir a liberdade humana: seria o de deixar de existir.”</p>
<p>Mikhail Bakunin</p>
</blockquote>
<p></p>Índice</p>
<p><a href="#problema">Problema</a></p>
<p><a href="#deus">Quem é Deus</a></p>
<p><a href="#dividir">Divisão do problema</a></p>
<p><a href="#primeiro">Primeiro argumento</a></p>
<p><a href="#segundo">Segundo argumentoa</a></p>
<p><a href="#terceiro">Terceiro argumento</a></p>
<p><a href="#quarto">Quarto argumento</a></p>
<p><a href="#quinto">Quinto argumento</a></p>
<p><a href="#sexto">Sexto argumento</a></p>
<p><a href="#setimo">Sétimo argumento</a></p>
<p><a href="#oitavo">Oitavo argumento</a></p>
<p><a href="#nono">Nono argumento</a></p>
<p><a href="#decimo">Décimo argumento</a></p>
<p><a href="#decimoprimeiro">Argumento Extra</a></p>
<p><a href="#decimosegundo">Argumento Extra</a></p>
<p><a href="#conclusao">Conclusão</a></p>
<p><a href="#autor">Referências</a></p>
<p>Há duas maneiras de estudar e procurar resolver o problema da existência de Deus.</p>
<p>A primeiro consiste em eliminar a hipótese Deus do campo das conjecturas plausíveis ou necessárias, por meio de uma explicação clara e precisa, isto é, por meio de uma exposição de um sistema positivo do Universo, das suas origens, dos seus desenvolvimentos sucessivos, dos seus fins. Esta exposição inutilizaria a ideia de Deus e destruiria antecipadamente a base metafísica em que se apoiam os teólogos e os filósofos espiritualistas.</p>
<p>Dado, porém, o estado atual dos conhecimentos humanos, em tudo o que tem sido demonstrado ou passa a demonstrar-se, verificado ou verificável, somos forçados a concluir que nos falta esta exposição e que não existe um sistema positivo do Cosmos. Existem, é certo, várias hipóteses engenhosas que não se chocam com o razão; sistemas mais ou menos aceitáveis que se apoiam numa série de investigações, que se baseiam na multiplicidade de observações contínuas e que dão um caráter de probabilidade impressionante. Também se pode afirmar, sem receio de ser desmentido, que esses sistemas, essas hipóteses, suportam vantajosamente as asserções deístas. Mas a falar a verdade, não há, sobre este posto, senão teses que não possuem ainda o valor da exatidão cientifica; — cada um, no fim das contas, tem a liberdade de preferir tal ou qual sistema a um outro que lhes é oposto; e a solução do problema assim apresentado afigura-nos, pelo menos na atualidade, cheio de reservas.</p>
<p>Os adeptos de todas as religiões aproveitam assim as vantagens que lhes oferece o estudo deste problema, bem árduo e bem complexo, não para o resolver por meio de afirmações concretas ou de raciocínios admissíveis, mas tão-somente para perpetuar a dúvida no espírito de seus correligionários, que é, para eles, o ponto de capital importância.</p>
<p>E nesta luta titânica entre o materialismo e o deísmo, luta em que as duas teses opostas se empenham e se reforçam para conseguir o triunfo, os deístas recebem rudes golpes; e, conquanto se encontrem numa postura de vencidos, ainda tem a petulância de se apresentar à multidão ignara como dignos cantores da vitória! Uma prova concludente do seu procedimento baixíssimo encontramo-la na maneira como se exprimem nos jornais da sua devoção; e é com essa comédia que procuram manter, com cajado de pastor, a imensa maioria do rebanho.</p>
<p>Também é isto que desejam ardentemente esses maus pastores.</p>
<h3 id="problema">Apresentação do Problema em Termos Precisos</h3>
<p>Todavia, há uma segunda maneira de estudar e de tentar a resolução da inexistência de Deus: consiste em examinar a existência de Deus que as religiões apresentam à adoração dos crentes.</p>
<p>Suponhamos que se nos depara um indivíduo sensato e refletido, que admite a existência de Deus — um Deus que não está envolto em nenhum mistério, um Deus que não se ignora nenhuma particularidade, um Deus que lhe confiou todo o seu pensamento e lhe transmitiu todas as suas confidências, e que nos diz:</p>
<p>— Ele fez isto e aquilo, e ainda isto e aquilo. Ele tem precedido e falado com tal fim e com tal razão. Ele quer tal coisa, mas também quer tal outra coisa. Ele recompensará tais ações, mas punirá tais outras. Ele fez isto e quer aquilo, porque é infinitamente sábio, infinitamente justo, infinitamente poderoso, infinitamente bom!</p>
<p>Ah! Que felicidade! Ora aqui está um Deus que se faz conhecer. Abandona o império do inacessível, dissipa as nuvens que o rodeiam, desce das alturas, conversa com os mortais, expõe-lhes o seu pensamento, revela-lhes a sua vontade e confia a alguns privilegiados a missão de espalharem a sua Doutrina, de propagarem a sua Lei, de a representarem enfim, cá em baixo, com plenos poderes para mandarem no Céu e na Terra.</p>
<p>Este Deus não é, com certeza, o Deus Força, Inteligência, Vontade, Energia, que, como tudo o que é Energia, Vontade, Inteligência, Força, pode ser alternadamente, segundo as circunstancias e, por consequência, indiferentemente, bom ou mau, útil ou inútil, justo ou iníquo, misericordioso ou cruel. Este Deus é o Deus em que tudo é perfeição e cuja existência não é nem pode ser compatível — visto que ele é perfeitamente sábio, justo, bom, misericordioso — senão com um estado de coisas criado por ele e no qual se afirmariam a sua infinita justiça, a sua infinita sabedoria, o seu infinito poder, a sua infinita bondade e a sua infinita misericórdia.</p>
<p>Este Deus é o Deus que, por meio de catecismo, nos insuflam no cérebro quando somos crianças; é o Deus vivo e pessoal, em honra do qual se erguem templos, a quem se rezam orações em borda, por quem se fazem sacrifícios estéreis e a quem pretendem representar, na Terra, todos os clérigos, todas as castas sacerdotais.</p>
<p>Este Deus não é o “desconhecido”, essa força enigmática, essa potência impenetrável, essa inteligência incompreensível, essa energia incognoscível, esse princípio misterioso: hipótese, enfim, que no meio da impotência para explicar o “como” e o “porquê” das coisas, o espírito do homem aceita complacente. Este Deus também não é o Deus especulativo dos metafísicos: é o Deus que os seus representantes nos tem descrito abundantemente e luminosamente detalhado. É o Deus das religiões, e como estamos na França, é o Deus dessa religião que a quinze séculos domina o nossa história: a religião católica ou cristã. É o Deus que nego e que vou discutir. É o Deus que estudaremos, se quisermos obter, desta exposição filosófica, algum proveito e algum resultado prático.</p>
<h3 id="deus">Quem é Deus?</h3>
<p>Visto que os encarregados de seus negócios no Terno tiveram a amabilidade de no-lo descrever com toda a pompa e luzimento, aproveitemos a fineza e examinemo-lo de perto, detidamente: para discutir uma coisa, é preciso, igualmente, conhecê-la bem.</p>
<p>Com um gesto potente e fecundo, este Deus fez todas as coisas do nada: o ser do não-ser. E, por sua própria vontade, substituiu o movimento pela inércia, a vida universal pela morte universal. É um Deus Criador!</p>
<p>Este Deus é o Deus que, terminada a obra da criação, em vez de volver à inatividade secular, ficando indiferente à coisa criada, ocupa-se de sua obra, interessando-se por ela, intervém nela quando o julga necessário, rege-a, administra-a, governa-a: é um Deus Governador ou Providência.</p>
<p>Este Deus é o Deus arvorado em Tribunal Supremo, obriga, depois da morte, a comparecer à sua presença todos os indivíduos. Uma vez aí, julga-as segundo os atos de suas vidas; pesa, na balança, as suas boas e más ações e pronuncia, em último extremo — sem apelo nem agravo — a sentença que fará do réu, pelos séculos dos séculos, o mais feliz ou o mais desgraçado dos seres: É um Deus Justiceiro ou Magistrado.</p>
<p>Logo, este Deus possui todos os atributos; e não é somente bom: é a Bondade Infinita; não é somente misericordioso: é o Misericórdia Infinita; não é somente poderoso: é o Poder Infinito; não é somente sábio: é a Sabedoria Infinita.</p>
<p>Em conclusão: tal é o Deus que eu nego e que por doze provas diferentes (em rigor bastaria uma só), vou demonstrar a inexistência.</p>
<h3 id="dividir">Divisão do Problema</h3>
<p>Dividi os meus argumentos em três séries: a primeira trataria particularmente do Deus-Criador e compor-se-á de seis argumentos; o segundo ocupar-se-á do Deus-Governador ou Providência, e contém quatro argumentos; a terceira apresentará o Deus-Justiceiro ou Magistrado, em dois argumentos. Em suma, seis argumentos contra o Deus-Criador, quatro contra o Deus-Governador e dois argumentos contra o Deus-Justiceiro. Estes doze argumentos constituem doze provas da inexistência de Deus.</p>
<p>Com este plano das minhas demonstrações será mais fácil seguir o curso do meu trabalho.</p>
<h3>Primeira série de argumentos: contra o Deus criador</h3>
<h5 id="primeiro">1º argumento: O gesto criador é inadmissível</h5>
<p>Que se entende por criar?</p>
<p>É tomar materiais diferentes, separados, mas que existem, e, valendo-se de princípios experimentados e aplicando-lhes certas regras conhecidas, aproximá-los, agrupá-los, associá-los, ajustá-los, para fazer qualquer coisa deles?</p>
<p>Não! Isso não é criar. Exemplos: podemos dizer que uma casa foi criada? Não, foi construída; podemos dizer que um móvel foi criado? Não, foi fabricado; podemos dizer que um livro foi criado? Não, foi composto e depois impresso.</p>
<p>Assim, pegar materiais que já existem e fazer qualquer coisa com eles não é criar.</p>
<p>Que é, pois, criar?</p>
<p>Criar… com franqueza, encontro-me indeciso para poder explicar o inexplicável, definir o indefinível. Procurei, contudo, fazer-me compreender.</p>
<p>Criar é tirar qualquer coisa do nada; é, com nada, fazer qualquer coisa do todo; é formar o existente do não-existente.</p>
<p>Ora, eu imagino que é impossível encontrar-se uma única pessoa dotada de razão que conceba e admita que do nada se possa tirar e fazer qualquer coisa. Suponhamos um matemático. Procurai o calculador mais autorizado; colocai-o diante de uma lousa e pedi-lhe que escreva zero sobre zeros. Terminada a operação, solicitai-lhe que os multiplique da forma que entender, que os divida até se cansar, que faça enfim toda a sorte de operações matemáticas, e haveis de ver como ele não extrairá, desta acumulação de zeros, uma única unidade.</p>
<p>Com nada, nada se pode fazer; de nada, nada se obtém. É por isso que o famoso aforismo de Lucrécio ex nihilo nihil é de uma certeza e de uma evidência manifesta. O gesto criador é um gesto impossível de admitir, é um absurdo.</p>
<p>Criar é, pois, uma expressão místico-religiosa, que pode ter algum valor aos olhos das pessoas a que agrada crer naquilo que não compreendem e a quem a fé que se impõe tanto mais quanto menos o percebem. Mas devemos convir que a palavra criar é uma expressão vazia de sentido para todos os homens cultos e sensatos, para quem uma palavra só tem valor quando representa uma realidade ou uma possibilidade.</p>
<p>Consequentemente, a hipótese de um ser verdadeiramente criador é uma hipótese que a razão repudia.</p>
<p>O ser criador não existe, não pode existir.</p>
<h5 id="segundo">2º argumento: O “puro espírito” não podia determinar o Universo</h5>
<p>Aos crentes que, a despeito de todo o raciocínio, se obstinam em admitir a possibilidade da criação, direi que, em todo o caso, é impossível atribuir esta criação ao seu Deus. O Deus deles é puro espírito. Portanto, é inteiramente impossível sustentar-se que o puro espírito, o imaterial, tenha podido determinar o Universo, o Material.</p>
<p>Eis o porquê:</p>
<p>O puro espírito não está separado do universo por uma diferença de grau, de quantidade, mas sim por uma diferença de natureza, de qualidade. De maneira que o puro espírito não é, nem pode ser, uma ampliação do Universo, assim como o Universo não é, nem pode ser, uma redução do puro espírito. Aqui a diferença não é somente uma distinção; é uma oposição: oposição de natureza — essencial, fundamental, irredutível, absoluta.</p>
<p>Entre o puro espírito e o Universo não há somente um fosso mais ou menos largo e profundo, fosso que possa, a rigor, encher-se ou franquear-se. Não. Entre o puro espírito e o Universo há um verdadeiro abismo, duma profundidade e de uma extensão tão imensos, que por colossais que sejam os esforços que se empreguem, não há nada nem ninguém que consiga enchê-lo ou franqueá-lo.</p>
<p>Reportando-me ao meu raciocínio, desafio o filósofo mais sutil, bem como o matemático mais consumado, a estabelecer uma relação, qualquer que ela seja (e, com a mais forte razão, uma relação tão direta quanto estreita, como a que liga a causa ao efeito) entre o puro espírito e o universo.</p>
<p>O puro espírito não suporta nenhuma aliança material. O puro espírito não tem forma nem corpo, nem linha, nem matéria, nem proporções, nem extensão, nem dureza, nem profundidade, nem superfície, nem volume, nem cor, nem som, nem densidade. Ora, no Universo, tudo é forma, corpo, linho, matéria, proporção, extensão, dureza, profundidade, superfície, volume, cor, som, densidade.</p>
<p>Como admitir que isto tenha sido determinado por aquilo? Impossível.</p>
<p>Chegando a este ponto da minha demonstração, a conclusão seguinte:</p>
<p>Vimos que a hipótese de um Deus verdadeiramente criador é inadmissível; que persistindo mesmo na crença desse poder, não pode admitir-se que o Universo, essencialmente material, tenha sido determinado por um puro espírito, essencialmente imaterial.</p>
<p>Mas se os crentes se obstinam em afirmar que foi o seu Deus o criador do Universo, nos impõe-se o dever de lhes fazer esta pergunta: segundo a hipótese Deus, onde se encontrava a Matéria, na sua origem, no seu princípio?</p>
<p>De duas, uma: ou a matéria estava fora de Deus, ou era o próprio Deus (a não ser que lhe queiram dar um terceiro lugar). No primeiro caso, se a matéria estava fora de Deus, Deus não teve necessidade de criá-la, visto que ela já existia; e, se ela coexistia com Deus, estava concomitantemente com ele, do que se depreende que Deus não é o criador.</p>
<p>No segundo caso, se a matéria não estava fora de Deus, encontrava-se no próprio Deus.</p>
<p>E, daqui, tiro a conclusão seguinte:</p>
<p>1º Que Deus não era puro espírito, porque encerrava em si uma partícula de matéria — e que partícula! A totalidade dos mundos materiais!</p>
<p>2º Que Deus, encerrando em si próprio a matéria, não teve a necessidade de criá-la, porque ela já existia. Assim, existindo a matéria, Deus não fez mais do que retirá-la de onde estava; e, neste caso, a criação deixa de ser um ato de verdadeira criação para se reduzir a um ato de exteriorização.</p>
<p>Nos dois casos não existe, pois, criação.</p>
<h5 id="terceiro">3º argumento: O perfeito não pode produzir o imperfeito</h5>
<p>Estou plenamente convencido de que se eu fizer a um religioso a pergunta: “Pode o imperfeito produzir o perfeito?”, ele responderia sem vacilar: — Não, o imperfeito não pode produzir o perfeito!</p>
<p>Pelas mesmas razões, e com a mesma força de exatidão, eu posso afirmar — O perfeito não pode produzir o imperfeito!</p>
<p>Mais: entre o perfeito e o imperfeito não há somente uma diferença de grau, de quantidade, mas uma diferença de qualidade, de natureza, uma oposição essencial, fundamental, irredutível, absoluta.</p>
<p>E mais ainda: entre o perfeito e o imperfeito não há somente um fosso, mais ou menos largo e profundo, mas um abismo tão vasto e tão estonteante, que ninguém o pode franquear ou entulhar. O perfeito é o absoluto, o imperfeito o relativo. Em presença do perfeito que é tudo, o relativo, o contingente não é nada; em presença do perfeito, o relativo não tem valor, não existe. E nem o talento de um matemático e nem o gênio de um filósofo serão capazes de estabelecer uma relação entre o relativo e o absoluto: a fortiori sustentamos a impossibilidade de evidenciar, neste caso, a rigorosa concomitância que deve necessariamente unir a Causa ao Efeito.</p>
<p>É, portanto, impossível que o perfeito haja determinando o imperfeito.</p>
<p>Além disso, há uma relação direta, fatal e até matemática entre uma obra e seu autor: tanto vale a obra quanto vale o autor, tanto vale o autor quanto vale a obra. E pela obra que se conhece o autor, como é pelo fruto que se conhece a árvore.</p>
<p>Se eu examino um texto mal redigido, em que se abundam os erros de ortografa e as frases são mal construídas, o estilo é pobre e frouxo, as ideias raras e banais, e os conhecimentos inexatos, eu sou incapaz de atribuir este péssimo escrito a um burilador de frases, a um dos mestres da literatura.</p>
<p>Se observo um desenho malfeito, em que as linhas estão mal traçadas, violadas as regras do perspectiva e da proporção, jamais me acudirá o pensamento de atribuir este esboço rudimentar a um professor, a um grande mestre, a um grande artista. Bem à menor hesitação direi: isto é obra de um aprendiz, de uma criança, certo de que pela obra se conhece o artista.</p>
<p>Ora, a natureza é bela, o Universo é grandioso. E eu admiro apaixonadamente — tanto o que mais admiro — os esplendores e as magnificências que nos oferecem estes espetáculos incessantes. Mas, por muito entusiasmado que eu seja das belezas naturais, e por grande que seja a homenagem que eu lhes tribute, não me atrevo o afirmar que o Universo é uma obra sem defeitos, irrepreensível, perfeita. E não acredito que haja alguém que me desminta.</p>
<p>Sim, o Universo é uma obra imperfeita.</p>
<p>Consequentemente, digo: há sempre, entre uma obra e seu autor, uma relação rigorosa, íntima, matemática. Ora, se o Universo é uma obra imperfeita, o autor desta obra não pode ser senão imperfeito.</p>
<p>Esse silogismo leva-me a admitir a imperfeição de Deus, e por consequência a negá-lo.</p>
<p>Mas eu posso ainda raciocinar assim: ou não é Deus o autor do Universo (exprimo desta forma a minha convicção), ou o é, na suposição dos religiosos. Neste caso, sendo o universo uma obra imperfeita, vosso Deus, ó crente, é também imperfeito.</p>
<p>Silogismo ou dilema, a conclusão do raciocínio é esta: o perfeito não pode determinar o imperfeito.</p>
<h5 id="quarto">4º argumento: O ser eterno, ativo, necessário, não pode, em nenhum momento, ter estado inativo ou ter estado inútil</h5>
<p>Se Deus existe é eterno, ativo e necessário.</p>
<p>Eterno? —  É-o por definição. É a sua razão de ser. Não se pode conceber que ele esteja enclausurado nos limites do tempo. Não se pode imaginar como tendo tido começo e venha a ter fim. Não pode haver aparição e desaparição. É de sempre.</p>
<p>Ativo? — É, e não pode deixar de ser. Segundo os religiosos, foi sua atividade que engendrou tudo quanto existe, como foi a sua atividade que se afirmou pelo gesto mais colossal e majestoso que imaginar se pode: a criação dos mundos.</p>
<p>Necessário? — É-o e não pode deixar de ser, visto que sem a sua vontade, nada existiria: ele é o autor de todas as coisas, o ponto inicial de onde saiu tudo, a fonte única e primeira de onde tudo emanou. Bastando-se a si próprio, dependeu de sua vontade que tudo fosse tudo ou que fosse nada.</p>
<p>Ele é, portanto: eterno, ativo e necessário.</p>
<p>Mas eu pretendo e vou demonstrar que se Deus é eterno, ativo e necessário, também deve ser eternamente ativo, e eternamente necessário. E que, por consequência, ele não pôde, em nenhum momento, ter sido inativo ou inútil, e que enfim, ele jamais criou.</p>
<p>Negar que Deus seja eternamente ativo equivale o dizer que nem sempre o foi, que chegou a sê-lo, que começou a ser ativo, que antes de o ser não o era. Dizer que foi pela criação que ele manifestou a sua atividade é admitir, ao mesmo tempo, que por milhares e milhares de séculos que antecederam a ação criadora, Deus esteve inativo.</p>
<p>Negar que Deus seja eternamente necessário equivale a admitir que ele nem sempre o foi, que chegou a sê-lo, que começou o ser necessário e que antes de o ser não o era. Dizer que a criação proclama e testemunha a necessidade de Deus equivale a admitir, ao mesmo tempo, que, durante milhares e milhares de séculos, que seguramente precedeu a ação criadora, Deus era inútil.</p>
<p>Deus ocioso e preguiçoso! Deus inútil e supérfluo! Que triste postura para um ser essencialmente necessário.</p>
<p>É preciso, pois, confessar que Deus é de todo o tempo ativo e de todo o tempo necessário.</p>
<p>Mas então Deus não pôde criar, porque a ideia de criação implica, de maneira absoluta, a ideia de começo, de origem. Uma coisa que começou é porque nem sempre existiu. Existiu necessariamente num tempo em que, antes de o ser, não o era. E, curto ou longo, este tempo foi que precedeu a coisa criada; é impossível suprimi-lo, visto que, de todos os modos, ele existe.</p>
<p>Assim, temos de concluir:</p>
<p>a) Ou Deus foi eternamente ativo e eternamente necessário, e só chegou a sê-lo por causa da criação (e, se é assim, antes da criação faltavam a este Deus dois atributos: a atividade e a necessidade; este Deus era um Deus incompleto; era só um pedaço de Deus e mais nada, que teve necessidade de criar para chegar a ser ativo e necessário, e completar-se).</p>
<p>b) Ou Deus é eternamente ativo e eternamente necessário, e neste caso tem criado eternamente. A criação é eterna, e o Universo jamais começou — existiu em todos os tempos, é eterno como Deus, é o próprio Deus, com o qual se confunde. E, sendo assim, o Universo não teve princípio — não foi criado.</p>
<p>Em conclusão: No primeiro caso, Deus antes da criação não era ativo nem era necessário: era um Deus incompleto, quer dizer, imperfeito, e, portanto, não existia. No segundo caso, sendo Deus eternamente ativo e eternamente necessário, não pôde chegar a sê-lo, como não pôde criar.</p>
<p>É impossível sair daqui.</p>
<h5 id="quinto">5º argumento: O ser imutável não criou</h5>
<p>Se Deus existe, é imutável, não se desfigura e nem se pode desfigurar. Enquanto que, na natureza, tudo se modifica, se metamorfoseia, se transforma; que nada é definitivo, mas que chega a sê-lo Deus, ponto fixo, imóvel no tempo e no espaço, não está sujeito a nenhuma modificação, não se transforma, nem pode transformar-se. É hoje o que era ontem, será amanhã o que é hoje. E tanto faz procurá-lo nos séculos passados, como nos séculos futuros: ele é, e será constantemente idêntico em si. Deus é imutável.</p>
<p>No entanto, eu sustento que, se ele criou, não é imutável, porque, neste caso, transmudou-se duas vezes.</p>
<p>Determinar-se a querer é mudar de posição. Ora, é evidente que há mudança entre o ser que quer uma coisa e o que, querendo-a, a põe em execução.</p>
<p>Se eu desejo e quero o que eu não desejava e nem queria a quarenta e oito horas, é porque se produziu em mim, ou a minha volta, uma ou várias circunstâncias que me levaram a querê-lo. Este novo desejo ou querer constitui uma modificação que não se pode por em dúvida, que é indiscutível.</p>
<p>Paralelamente: agir, ou determinar-se a agir, é modificar-se.</p>
<p>Esta dupla modificação — querer e agir — é tanto mais considerável e saliente quando é certo que se trata de uma resolução grave, de uma ação importante.</p>
<p>Deus criou, dizeis vós, crentes. Então modificou-se duas vezes: a primeiro, quando se determinou a criar; a segunda, quando resolveu por em prática sua determinação, completando o gesto criador.</p>
<p>Se ele se modificou duas vezes, não é imutável. E, se não é imutável, não é Deus — não existe.</p>
<p>O ser imutável não criou.</p>
<h5 id="sexto">6º argumento: Deus não criou sem motivo; mas é impossível encontrar um único motivo que o levasse a criar</h5>
<p>De qualquer forma que se pretende examiná-la, a criação é inexplicável, enigmática, falha de sentido.</p>
<p>Há uma coisa que salta à vista de todos: se Deus criou, como vós dizeis, não pôde ter realizado este ato grandioso — cujas consequências deviam ser, fatalmente, proporcionais ao próprio ato, e por conseguinte incalculáveis — sem que fossem determinado por uma razão de primeiro ordem.</p>
<p>Pois muito bem. Qual foi esta razão? Porque motivo tomou Deus a resolução de criar? Que móbil o impulsionaria a isto? Que desejo germinaria em seu cérebro? Qual seria o seu intuito? Que ideia o perseguiria? Que fim perseguiria ele?</p>
<p>Multiplicais, nesta ordem de ideias, as perguntas; gravito, conforme quiserdes, em torno deste problema; examinai-o em todos os seus aspectos e em todos os sentidos, e eu desafio seja quem for a que o resolve em outro sentido que não seja o das incoerências.</p>
<p>Por exemplo: Eis uma criança educada na religião cristã. O seu catecismo afirmou-lhe, e os seus mestres confirmam, que foi Deus que a criou e a colocou no mundo. Suponhamos que a criança faz a si própria a pergunta: porque é que Deus me criou e me lançou no mundo?, e que quer obter uma resposta judiciosa, racional. Nunca obterá.</p>
<p>Suponhamos ainda que a criança, confiando na experiência e no saber de seus educadores, persuadida do caráter sagrado de que eles — padres ou pastores — estão revestidos, possuindo luzes especiais e graças particulares; convencido de que, pela sua santidade, estão mais próximos de Deus e, portanto, melhores iniciados que elas nas verdades reveladas; suponhamos que esta criança tem a curiosidade de perguntar aos seus mestres por que e para que Deus a criou e a pôs no mundo, e eu afirmo que os mestres são incapazes de contestar a essa simples interrogação com uma resposta plausível, sensata. Não lhe poderão dar, porque, em verdade, ela não existe.</p>
<p>Mas, rodeemos bem a questão e aprofundemos o problema. Com o pensamento, examinaremos Deus antes da criação. Tomemo-lo mesmo no seu sentido absoluto. Está completamente só; bastando-se a si próprio. E perfeitamente sábio, perfeitamente feliz, perfeitamente poderoso. Ninguém lhe pode acrescentar sabedoria, ninguém lhe pode aumentar a felicidade, ninguém lhe pode fortificar o poderio.</p>
<p>Este Deus não experimenta nenhum desejo, visto que a sua felicidade é infinita. Não pode perseguir nenhum fim, visto que nada falta à sua perfeição. Não pode ter nenhum intuito, visto que nada falta ao seu poder. Não pode determinar-se a fazer seja o que for, visto que não tem nenhuma necessidade.</p>
<p>Eia! Filósofos profundos, pensadores sutis, teólogos prestigiosos, respondei a esta criança que vos interroga e dizei-lhe por que é que Deus a criou e lançou no mundo!</p>
<p>Eu estou tranquilo. Vós não lhe podeis responder, a não ser que lhe digais: “Os mistérios de Deus são impenetráveis”! — e aceitais esta resposta como suficiente. E fareis bem, abstendo-vos de lhes dar outra resposta, porque esta outra resposta — previno-vos caritativamente — cava a ruína de vosso sistema e o derribamento de vosso Deus. A conclusão impõe-se, lógica, impiedosa: Deus, se criou, criou sem motivos, sem saber por que, sem ideal.</p>
<p>Sabeis onde nos conduzem as consequências de tal conclusão? Vamos vê-las.</p>
<p>O que diferencia os atos de um homem dotado de razão dos atos de um louco, o que determina que um seja responsável e o outro irresponsável, é que um homem dotado de razão sabe sempre — ou pode chegar o sabê-lo — quando procede, quais são os móbiles que o impulsionam, quais são os motivos que o levam a praticar aquilo que pensava. Quando se trata de uma ação importante, cujas consequências podem hipotecar gravemente as suas responsabilidades, é preciso que o homem entre na posse de sua razão, se concentre, se entregue a um sério exame de consciência, persistente e imparcial, exame que, pelas suas recordações, reconstitua o quadro dos acontecimentos de que ele foi agente. Em resumo, é preciso que ele procure reviver as horas passadas para que possa discernir quais foram as causas e o mecanismo dos movimentos que o determinaram a obrar. Frequentemente, não pode vangloriar-se das causas que o impulsionaram, e que, amiúde, o levam a corar de vergonha. Mas, quaisquer que sejam os motivos, nobres ou vis, generosos ou grosseiros, ele chega sempre o descobri-los.</p>
<p>Um louco, pelo contrário, precede sem saber por que; e, uma vez realizado o ato, por grandes que sejam as responsabilidades que dele possam deriva-se, interrogai-o, encerrai-o, se quiserdes, numa prisão, e apertai-o com perguntas: o pobre demente não vos balbuciará senão coisas vagas, verdadeiras incoerências.</p>
<p>Portanto, o que diferencia os atos de um homem sensato de um homem insensato, é que os atos dos primeiros podem explicar-se, tem uma razão de ser, distinguem-se neles a causa e o efeito, a origem e o fim, enquanto que os atos do segundo não se podem explicar, porque um louco é incapaz de discernir a causa e o que o levam a realizá-los.</p>
<p>Pois bem! Se Deus criou sem motivo, sem fim, procedeu como um louco. E, neste caso, a criação aparece-nos como um ato de demência.</p>
<h3>Duas objeções capitais</h3>
<p>Para terminar com o Deus da criação, parece-me indispensável examinar duas objeções.</p>
<p>Os leitores sabem muito bem, sobre este assunto, abundam objeções. Por isso quando falo em duas objeções, refiro-me a duas objeções capitais clássicas.</p>
<p>Estas duas objeções têm tanto mais importância quanto é certo que, com a beldade da discussão, se podem englobar todas as outras nestas duas.</p>
<h5>1ª objeção: “Deus escapa-vos!”</h5>
<p>Dizem-me:</p>
<p>“O senhor não tem o direito de falar de Deus segundo a forma que o faz. O senhor não nos apresenta senão um Deus caricaturado, sistematicamente reduzido a proporções que seu cérebro abarca. Esse Deus não é nosso Deus. O nosso Deus não o pode o senhor concebê-lo, visto que lhe é superior, escapando por isso à suas faculdades intelectuais. Fique sabendo que o que é fabuloso, gigantesco para o homem mais forte e mais inteligente, é para Deus um simples jogo de crianças. Não se esqueça que a Humanidade não pode mover-se no mesmo plano que a Divindade. Não perca de vista que é tão impossível ao homem compreender a maneira como Deus procede, como os minerais imaginar como vivem os vegetais, como os vegetais conceber o desenvolvimento dos animais, e como os animais saber como vivem e operam os homens.</p>
<p>Deus paira a umas alturas que o senhor é incapaz de atingir ocupa montanhas inacessíveis ao senhor. Qualquer que seja o grau de desenvolvimento de uma inteligência humana; por muito importante que seja o esforço realizado por essa inteligência; seja qual for a persistência deste esforço, jamais poderá elevar-se até Deus. Lembre-se, enfim, que, por muito vasto que seja o cérebro do homem, ele é finito, não podendo, por consequência, conceber Deus, que é infinito.</p>
<p>Tenha pois a lealdade e a modéstia de confessar que não lhe é possível compreender nem explicar, não o cabe o direito de negar”.</p>
<p>Eu respondo aos deístas:</p>
<p>Dais-me conselhos de humildade que estou disposto a aceitar. Fazeis me lembrar que sou um simples mortal, o que legitimamente reconheço e não procuro olvidar-me.</p>
<p>Dizeis-me que Deus me ultrapassa e que o desconheço. Seja. Consinto em reconhecê-lo; afirmo mesmo que o finito não pode compreender o infinito, porque é uma verdade tão certa e tão evidente, que não está em meu ânimo fazer-lhe qualquer oposição. Vede, pois, até aqui estamos de acordo, com o que espero, ficareis muito contentes.</p>
<p>Somente, senhores deístas, permiti que, por meu turno, eu vos dê os mesmos conselhos de humildade, para terdes o franqueza de me responder estas perguntas: Vós não sois homens como a mim? A vós, Deus não se depara como para a mim? Esse Deus não vos escapa como a mim? Tereis vós a pretensão de moverdes no mesmo plano da divindade? Tereis igualmente a mania de pensar e a loucura de crer que, de um voo, podereis chegar às alturas que Deus ocupa? Sereis presunçosos ao extremo de afirmar que o vosso cérebro, o vosso pensamento que é finito, possa compreender o infinito?</p>
<p>Não vos faço a injuria, senhores deístas, de acreditar que sustentais uma extravagância venal. Assim, pois, tende a modéstia e a lealdade de confessar que, se me é impossível compreender e explicar Deus, vós tropeçais no mesmo obstáculo. Tende, enfim, a probidade de reconhecer que, se eu não posso conceber nem explicar Deus, não o podendo, portanto, negar, a vós, como a mim, não vos é permitido concebê-lo e não tendes, por consequência, o direito de afirmá-lo.</p>
<p>Não julgueis, no entanto, que, por causa disto, ficamos na mesma situação que antes. Foste vós que, primeiramente, afirmastes a existência de Deus; deveis, pois, ser os primeiros a pôr de parte vossas afirmações. Sonharia eu, alguma vez, com negar a existência de Deus, se vós não tivésseis começado a afirmá-la? E se, quando eu era criança, não me tivessem imposto a necessidade de acreditar nele? E se, quando adulto, não tivesse ouvido afirmações nesse sentido? E se, quando homem, os meus olhos não tivessem constantemente contemplado os templos elevados a esse Deus? Foram as vossas afirmações que provocaram as minhas negações.</p>
<p>Cessai de afirmar que eu cessarei de negar.</p>
<h5>2ª objeção: “Não há efeito sem causa”</h5>
<p>A segunda objeção parece-nos mais invulnerável. Muitos indivíduos consideram-na ainda sem réplica. Esta objeção provém dos filósofos espiritualistas: Não há efeito sem causa. Ora, o Universo é um efeito; e, como não há efeito sem causa, esta causa é Deus.</p>
<p>O argumento é bem apresentado; parece, mesmo, bem construído e bem carpintejado. O que resto saber é se tudo quanto ele encerra é verdadeiro.</p>
<p>Em boa lógica, este raciocínio chama-se silogismo. Um silogismo é um argumento composto por três proposições: a maior, a menor e a consequência, e compreende duas partes: as premissas, constituídas pelas duas primeiras proposições e a conclusão, representada pela terceira. Para que um silogismo seja inatacável, é preciso:</p>
<p>1º que a maior e a menor sejam exatas;</p>
<p>2º que a terceira proposição dimane logicamente as duas primeiras.</p>
<p>Se o silogismo dos filósofos espiritualistas reúne estas duas condições, é irrefutável e nada mais me resta senão aceitá-lo; mas, se lhe falta uma só dessas condições, então o silogismo é nulo, sem valor, e o argumento destrói-se por si mesmo.</p>
<p>A fim de conhecer o seu valor, examinemos as três proposições que o compõe.</p>
<h6>1ª proposição (maior): “Não há efeito sem causa”.</h6>
<p>Filósofos, tendes razão. Não há efeito sem causa: nada mais exato. Não há, não pode haver, efeito sem causa. O efeito não é mais do que a continuação, o prolongamento, o limite da causa. Quem diz efeito diz causa. A ideia de efeito provoca, necessariamente e imediatamente a ideia de causa. Se, ao contrário, se concebe um efeito sem causa, isto seria o efeito do nada, o que equivaleria a crer no absurdo.</p>
<p>Sobre esta primeira proposição, estamos, pois, de acordo.</p>
<h6>2ª proposição (menor): “Ora, o Universo é um efeito”.</h6>
<p>Antes de continuar, peço explicações:</p>
<p>Sobre o que se apoia esta afirmação tão franca e tão categórica? Qual o fenômeno, ou conjunto de fenômenos, na qual a verificação, ou conjunto de verificações, que permitem uma afirmação tão rotunda?</p>
<p>Em primeiro lugar, comecemos suficientemente o Universo? Temo-lo estudado profundamente, temo-lo examinado, investigado, compreendido, para que nos seja permitido fazer afirmações desta natureza? Temos penetrado nas suas entranhas e explorado os seus espaços incomensuráveis? Já descemos a profundeza do oceano? Conhecemos todos os domínios do Universo? O Universo já nos declarou todos os seus segredos? Já lhe arrancamos todos os véus, penetramos todos os seus mistérios, descobrimos todos os seus enigmas? Já vimos tudo, apalpamos tudo, sentimos tudo, entendemos tudo, observamos tudo, afrontamos tudo? Não temos nada mais que aprender? Não nos resta nada mais que descobrir? Em resumo, estamos em condições de fazer uma apreciação formal do Universo?</p>
<p>Supomos que ninguém ousará responder afirmativamente a todas estas questões; e seria digno de lástima todo aquele que tivesse a tenebridade e a insensatez de afirmar que conhece o Universo.</p>
<p>O Universo! — quer dizer não somente este ínfimo planeta que habitamos e sobre o qual se arrastam as nossas carcaças; não somente os milhões de astros que conhecemos e que fazem parte do nosso sistema solar, ou que descobrimos com o decorrer dos tempos, mas ainda, esses mundos, aos quais, com conjectura, conhecemos a existência, mas cuja distancia e o número restam incalculáveis!</p>
<p>Se eu dissesse “o universo é uma causa”, tenho a certeza que desencadeariam imediatamente contra mim as vaias e os protestos de todos os religiosos; e, todavia, a minha afirmação não era mais descabelada que a deles. Eis tudo.</p>
<p>Se me inclino sobre o Universo, se o observo quanto me permitir o homem contemporâneo, os conhecimentos adquiridos, verificarei que é um conjunto inacreditavelmente complexo e denso, uma confusão impenetrável e colossal de causas e de efeitos que se determinam, se encadeiam, se sucedem, se repetem e se interpenetram. Observarei que o todo leva uma cadeia sem fim, cujos elos estão indissoluvelmente ligados.</p>
<p>Certificar-me-ei de que cada um destes elos é, por sua vez, causa e efeito: efeito da causa que o determinou, causa do efeito que se lhe segue.</p>
<p>Quem poderá dizer: “Eis aqui o primeiro elo — o elo causa”? Quem poderá afirmar: “Eis o último elo — elo efeito”? E quem poderá ainda dizer: “Há necessariamente uma causa número um e um efeito número… último”?</p>
<p>À segunda proposição, “ora, o Universo é um efeito”, falta-lhe uma condição indispensável: a exatidão. Por consequência, o famoso silogismo não vale nada.</p>
<p>Acrescento mesmo que, no caso em que esta segunda proposição fosse exata, faltaria estabelecer, para que a conclusão fosse aceitável, se o Universo é o próprio efeito de uma Causa única, de uma Causa primeira, da Causa das Causas, de uma Causa sem Causa, da Causa eterna.</p>
<p>Espero, sem me inquietar, esta demonstração, porque é uma demonstração que se tem desejado muitas vezes, sem que ninguém no-la desse; é também uma demonstração, da qual se pode afirmar, sem receio de desmentido, que jamais poderá se estabelecer de uma forma séria, positiva e científica.</p>
<p>Por último: admitindo que o silogismo fosse irrepreensível, ele poderia voltar-se facilmente contra a tese do Deus-Criador, colocando-se a favor da minha demonstração.</p>
<p>Expliquemos: “não há efeito sem causa!” — Seja! — “o Universo é um efeito!” — De acordo! — “Logo este efeito tem uma causa e é esta causa que chamamos Deus! — Pois seja!</p>
<p>Mas não vos entusiasmeis, deístas; escutai-me, porque ainda não triunfastes.</p>
<p>Se é evidente que não há efeito sem causa, é também rigorosamente exato que não há causa sem efeito. Não há, não pode haver, causa sem efeito. Que diz causa, diz efeito. A ideia de causa implica necessariamente e chama a ideia de efeito. Porque uma causa sem efeito seria uma causa do nada, o que seria tão absurdo quanto o efeito do nada. Que fique, pois, bem entendido: não há causa sem efeito.</p>
<p>Vós, deístas, afirmais, enfim, que o Deus-Causa é eterno. Desta afirmação concluo que o Universo-Efeito é igualmente eterno, visto que a uma causa eterna, corresponde, indubitavelmente, a um efeito eterno. Se pudesse ser de outro modo, quer dizer, se o Universo tivesse começado, durante os milhares e milhares de séculos que, talvez, precederam a criação do Universo, Deus teria sido uma causa sem efeito, o que é impossível; uma causa de nada, o que seria absurdo.</p>
<p>Em conclusão: se Deus é eterno, o Universo também o é: e, se o Universo também é eterno, é porque ele nunca principiou, é que jamais foi criado.</p>
<p>É clara a demonstração?</p>
<h3>Segunda série de argumentos: Contra o Deus-governador</h3>
<h5 id="setimo">7º argumento: O governador nega o criador</h5>
<p>São muitíssimos — formam legiões — os indivíduos que, apesar de tudo, se obstinam em crer. Concebo que, a rigor, se possa crer na existência de um criador perfeito, como também concebo que se possa crer na existência de um governador necessário. Mas, o que me parece impossível é que, ao mesmo tempo, se possa crer racionalmente num e noutro, porque estes dois seres perfeitos se excluem categoricamente: afirmar um é negar o outro; proclamar a perfeição do primeiro é confessar a inutilidade do segundo; sustentar a necessidade do segundo é negar a perfeição do primeiro.</p>
<p>Por outras palavras: pode-se crer na perfeição ou na necessidade do outro; mas o que não tem a menor sombra de lógica é crer na perfeição dos dois. É preciso, pois, escolher qualquer deles.</p>
<p>Se o Universo criado por Deus tivesse sido uma obra perfeita; se, no seu conjunto, como nos seus pormenores, esta obra não apresentasse nenhum defeito; se o mecanismo desta criação gigantesca fosse irrepreensível; se a sua perfeição fosse de modo que a ninguém despertasse a menor suspeita de qualquer desarranjo ou de qualquer avaria; se, enfim, a obra fosse digna deste operário genial, deste artista incomparável, desse construtor fantástico a que chamam Deus, a necessidade de um governador nunca se teria sentido.</p>
<p>É que é lógico supor que, uma vez a formidável máquina fosse posta em movimento, nada mais haveria a fazer do que abandoná-la a si própria, visto que os acidentes seriam impossíveis. Não seria preciso este engenheiro, este mecânico, para vigiar a máquina, para a dirigir, para a reparar, para a afinar, enfim. Não, este engenheiro seria inútil, este mecânico não teria razão de ser.</p>
<p>E, neste caso, o Deus-Governador era também inútil. Se o Governador existe, é porque a sua intervenção, a sua vigilância são indispensáveis. A necessidade do Governador é como que um insulto, como um desafio lançado ao Criador; a sua intervenção corrobora o desconhecimento, a incapacidade, a impotência desse criador.</p>
<p>O Deus-Governador nega a perfeição do Deus-Criador.</p>
<h5 id="oitavo">8º argumento: A multiplicidade dos deuses prova que não existe nenhum deles</h5>
<p>O Deus-Governador é, e não pode deixar de ser, poderoso e justo, infinitamente poderoso e infinitamente justo.</p>
<p>Ora, eu afirmo que a multiplicidade das religiões atesta que falta a este Deus poder ou justiça, se não, ambas as coisas.</p>
<p>Não falemos dos deuses mortos, dos cultos abolidos, das religiões esquecidas, que se contam por milhares e milhares. Falemos somente das religiões de nossos dias. Segundo os cálculos mais bem fundados, há, presentemente, oitocentas religiões, que se disputam o império das mil e seiscentas milhões de consciências que povoam o nosso planeta. Ninguém pode duvidar que cada uma destas religiões reclama para si privilégio de que só o seu Deus é que é o verdadeiro, autêntico, o indiscutível, o único, e que todos os outros Deuses são Deuses risíveis, Deuses falsos, Deuses de contrabando e de pacotilha, e que, portanto, é uma obra piedosa combatê-los e pulverizá-los.</p>
<p>A isto, ajunta: Se em vez de oitocentas religiões, não houvesse senão cem ou dez, ou duas, o meu argumento teria o mesmo valor.</p>
<p>Pois bem, afirmo novamente que a multiplicidade destes Deuses atesta que não existe nenhum, certificando, ao mesmo tempo, que Deus não é todo-poderoso nem sumamente justo.</p>
<p>Se fosse poderoso teria podido falar a todos os indivíduos com a mesma facilidade com que falou isoladamente a alguns. Ter-se-ia mostrado, ter-se-ia revelado a todos sem empregar mais esforços do que o que empregou para se apresentar a poucos.</p>
<p>Um homem — qualquer que seja — não pode mostrar-se nem falar senão a um número reduzido de indivíduos: os seus órgãos vocais têm uma persistência que não pode exceder certos limites. Mas Deus… Deus pode falar a todos os indivíduos — por muito grande que seja o número — com a mesma facilidade que falaria a uns poucos. Quando se eleva, a voz de Deus pode e deve perpetuar-se nos quatro pontos cardeais! O verbo divino não conhece distâncias nem obstáculos. Atravessa os oceanos, escala as alturas, franqueia os espaços, sem a menor dificuldade.</p>
<p>E visto que ele quis — é a religião que o afirma — falar com os homens, revelar-se-lhes, confiar-lhes os seus desejos, indicar-lhes a sua vontade, fazer-lhes conhecer a sua lei, bem teria podido fazê-lo a todos e não a um punhado de privilegiados.</p>
<p>Mas Deus não fez assim, visto que uns o negam, outros o ignoram, e outros, enfim, opõe tal Deus a tal outro Deus dos seus concorrentes.</p>
<p>Nestas condições não será mais sensato pensar que ele não falou a ninguém, e que as múltiplas revelações que me atribuem, não são, senão, múltiplas imposturas, ou arma que, se ele falou a uns poucos, é porque era incapaz de falar com todos?</p>
<p>Sendo assim, eu acuso-o de impotência. E se não quiserdes que o acuse de impotência, acuso-o de injustiça. Que pensar, com efeito, de um Deus que se mostra a um reduzido número e que se esconde das outras? Que pensar de um Deus que fala para uns e que, para outros, guarda o mais profundo silêncio?</p>
<p>Não esqueçais que os representantes desse Deus afirmam que ele é o pai de todos: e que todos, qualquer que seja o seu título ou grau, são os filhos bem amados desse Pai que reina lá no céu! Pois, muito bem, que pensais desse pai que, exuberante da ternura para alguns privilegiados, os desperta, revelando-se-lhes evitando-se as angustias da dúvida, arrancando-o das torturas da hesitação, enquanto que, violentamente, condena a maioria de seus filhos aos tormentos da incerteza? Que pensais desse pai que, no meio de seu esplendor de Majestade, se mostra a uma parte de seus filhos, enquanto que, para a outra, fica envolto nas mais profundas trevas? Que pensais desse pai que, exigindo de seus filhos a prática de um culto, com o seu contingente de respeitos e adorações, chama só alguns deles para escutarem a sua palavra de Verdade, enquanto que, com um propósito deliberado, nega aos demais esta distinção, este insigne favor?</p>
<p>Se julgais que este pai é justo e bom, não vos surpreendas com a minha apreciação, que é muito diferente:</p>
<p>A multiplicidade de religiões proclama que a Deus faltou poder ou justiça. Ora, Deus deve ser infinitamente poderoso e infinitamente justo — são os religiosos que o afirmam. E se lhe falta um destes dois atributos — poder ou justiça — não é perfeito: não sendo perfeito, não tem razão de ser, não existe.</p>
<p>A multiplicidade dos Deuses e das religiões demonstra que não existe nenhum deles.</p>
<h5 id="nono">9º argumento: Deus não é infinitamente bom: é o inferno que o prova</h5>
<p>O Deus-Governador ou Providência é, deve ser, infinitamente bom, infinitamente misericordioso. Mas a existência do Inferno demonstra-nos que não é assim.</p>
<p>Atentai bem ao meu raciocínio: Deus podia — porque é livre — não nos ter criado; mas criou-nos. Deus podia — porque é todo poderoso — ter-nos criado todos bons; mas criou-nos bons e maus. Deus podia — porque é bom — admitir-nos todos, após a morte, no seu Paraíso, contentando-se, como castigo, com o tempo de sofrimento e atribulações que passamos na Terra. Deus podia, em suma — porque é justo — não admitir em seu Paraíso senão os bons, recusando ali lugar aos perversos; mas, neste caso, deveria destruir totalmente os maus com a morte, e jamais condená-lo aos sofrimentos do Inferno. E isto porque quem pode criar, pode destruir; quem tem poder para dar a vida, também tem o poder para tirá-la, para aniquilá-la.</p>
<p>Vejamos: vós não sois deuses. Vós não sois infinitamente bons, nem infinitamente misericordiosos. Sem vos atribuir qualidades que não possuís, eu tenho a certeza de que, se estivesse em vossas mãos — sem que isso vos exigisse um grande esforço, e sem que, de aí, resultasse para nós algum prejuízo moral ou material — evitar a um ser humano uma lágrima, uma dor, um sofrimento, eu tenho a certeza, repito, que o faríeis imediatamente, sem vacilar nem titubear. E, todavia, vós não sois infinitamente misericordiosos.</p>
<p>Sereis, por acaso, melhores e mais misericordiosos que o Deus dos cristãos?</p>
<p>Porque, enfim, o Inferno existe. A Igreja faz alarde dele: é a horrível visão, com a ajuda da qual semeia o pavor no cérebro das crianças e dos velhos, e entre os pobres de espírito e os medrosos; é o espectro que se estala na cabeceira dos moribundos, na hora em que a morte os arrebata toda a coragem, toda a energia, toda a lucidez.</p>
<p>Pois bem, o Deus dos cristãos, esse Deus que dizem cheio de piedade, de perdão, de indulgência, de bondade e de misericórdia, precipita para todo o sempre, uma parte dos seus filhos, num antro de torturas as mais cruéis, e de suplicias as mais horrendas.</p>
<p>Oh! Como ele é bom! Como ele é misericordioso!</p>
<p>Vós conheceis certamente estas palavras das escrituras: “Muitos serão os chamados, mas poucos os eleitos”. Bem abusos do seu valor, estas palavras significam que o número de salvos será ínfimo, enquanto que o número de condenados há de ser considerável. Esta afirmação é de uma crueldade tão monstruosa que os deístas têm procurado dar-lhe um outro sentido.</p>
<p>Mas pouco importa: o Inferno existe, e é evidente que os condenados — muitos ou poucos — aí sofrerão os mais dolorosos tormentos.</p>
<p>Agora, pergunto eu: a quem podem beneficiar os tormentos dos condenados? Aos eleitos? — Evidente que não. Por definição, os eleitos serão os justos, os virtuosos, os fraternais, os compassivos: e seria absurdo supor que a sua felicidade, já incomparável, pudesse ser aumentada com o espetáculo de seus irmãos torturados. Aos próprios condenados? — também não, porque a igreja afirma que o suplicio desses desgraçados jamais acabará; e que, pelos séculos dos séculos, os seus sofrimentos serão tão horripilantes como no primeiro dia.</p>
<p>Então?… Então, aparte os eleitos e aparte os condenados, não há senão Deus, não pode haver senão ele. É, pois, Deus, quem obtém benefícios aos sofrimentos dos condenados? É, pois, ele, esse pai infinitamente bom, infinitamente misericordioso, que se regozija sadicamente com as dores e que voluntariamente condena os seus filhos?</p>
<p>Ah! Se isto é assim, esse Deus aparece-nos como carrasco mais feroz, como o inquisidor mais implacável que imaginar se pode.</p>
<p>O inferno prova que Deus não é bom nem misericordioso — a existência de um Deus de bondade é incompatível com a existência do inferno.</p>
<p>E de duas uma: ou o inferno não existe, ou Deus não é infinitamente bom.</p>
<h5 id="decimo">10º argumento: O problema do mal</h5>
<p>É o problema do mal que me fornece material para o meu último argumento contra o Deus-Governador, e, simultaneamente, para o meu primeiro argumento contra o Deus-justiceiro.</p>
<p>Eu não digo que a existência do mal — mal físico e mal moral — seja incompatível com a existência de Deus; o que digo é que é incompatível com o mal a existência de um Deus infinitamente poderoso e infinitamente bom.</p>
<p>O argumento é conhecido, ainda que o não seja senão pelas múltiplas refutações — sempre impotentes — que se lhes tem apresentado. Remontam-no a Epicuro. Tem, portanto, mais de vinte séculos de existência: mas, por velho que seja, conserva ainda todo o seu vigor. Esse argumento é o seguinte:</p>
<p>O mal existe. Todos os seres sensíveis conhecem o sofrimento. Deus, que tudo sabe, não pode ignorá-lo. Pois bem, de duas, uma: Ou Deus quer suprimir o mal e não pode; ou Deus pode suprimir o mal e não quer.</p>
<p>No primeiro caso, Deus pretendia suprimir o mal, porque era bom, porque compartilhava das dores que nos aniquilam, porque participava dos sofrimentos que suportamos. Ah! Se isso dependesse dele! O mal seria suprimido e a felicidade reinaria sobre a Terra…</p>
<p>Mais uma vez Deus é bom, mas não pode suprimir o mal — não é todo poderoso.</p>
<p>No segundo caso, Deus podia suprimir o mal. Bastava que o quisesse para que o mal fosse abolido. Ele é todo poderoso e não quer suprimir o mal; portanto, não é infinitamente bom.</p>
<p>Aqui, Deus é todo poderoso, mas não é bom; acolá, Deus é bom mas não é todo poderoso. Para admitir a existência de Deus, não basta que ele possua uma destas perfeições: poder ou bondade. É indispensável que possua as duas.</p>
<p>Este argumento nunca foi refutado. Entendamo-nos: ao dizer nunca foi refutado quero dizer que, racionalmente, ninguém a pode ainda refutar, embora tenham ensaiado isso muitas vezes. O ensaio de refutação mais conhecido é este:</p>
<p>Vós apresentais em termos errôneos o problema do mal. É um equivoco atirar para cima de Deus toda a responsabilidade. Bem, é certo que o mal existe — é inegável; mas só o homem é responsável por ele. Deus não quis que o homem fosse um autômato, uma máquina, que obedece cega e fatalmente. Ao criá-lo, Deus deu-lhe completa liberdade — fez dele um ser inteiramente livre; e, conforme com essa liberdade, que generosamente lhe outorgou, concedeu-lhe a faculdade de fazer dela, em todas as circunstâncias, o uso que quisesse. E se o homem, em vez de fazer uso nobre e justiceiro deste bem inestimável, faz dele um uso criminoso, porque seria injusto: devemos acusar mais é o homem, o que é razoável.</p>
<p>Eis a clássica objeção. Que é que ela vale? Nada!</p>
<p>Eu explico-me: façamos distinção entre o mal físico e o mal moral. O mal físico é a doença, o sofrimento, o acidente, a velhice, com o seu cortejo de vícios e enfermidades; é a morte, que implica perda de seres que amamos. Há crianças que nascem e que morrem, dias depois de seu nascimento, e cuja vida foi um sofrimento permanente. Há uma enorme multidão de seres humanos para quem a vida não é mais do que uma longa série de dores e aflições: seria preferível que não tivessem nascido. E, na ordem natural, as epidemias, os cataclismos, os incêndios, as secas, as inundações, as tempestades, a fome, constituem uma soma de trágicas fatalidades que originam a dor e a morte.</p>
<p>Quem ousará dizer que o homem é o responsável por este mal físico? Quem não compreende que se Deus criou o Universo, dotando-o com as formidáveis leis que o regem, o mal físico não é senão uma destas fatalidades que resultam de um jogo normal das forças da natureza? Quem não compreende que o autor responsável destas calamidades é, com toda a certeza, quem criou o Universo e quem o governa?</p>
<p>Suponho que, sobre este ponto, não há contestação possível. Deus que governa o Universo, é o responsável pelo mal físico. Esta resposta seria suficiente, e, no entanto, vou continuar.</p>
<p>Eu entendo que o mal moral é tão imputável a Deus quanto o mal físico. Se Deus existe, foi ele que presidiu à organização do mundo físico. Por consequência, o homem, vítima do mal moral, como do mal físico, não pode ser responsável por um nem por outro.</p>
<p>Vamos, pois, ver agora na terceira e última série de argumento, o que tenho a dizer sobre o mal moral.</p>
<h3>Terceira serie de argumentos: Contra o Deus justiceiro</h3>
<h5 id="decimoprimeiro">11º argumento: Irresponsável, o homem não pode ser castigado nem recompensado</h5>
<p>Que somos nós? Presidimos às condições de nosso nascimento? Fomos consultados sobre se queríamos nascer? Fomos chamados a traçar o nosso destino? Tivemos, sobre qualquer destas questões, voz ou voto?</p>
<p>Se cada um de nós tivesse voz e voto para escolher, desde o nascimento, a saúde, a força, a beleza, a inteligência, a coragem, a bondade, etc…, seguramente que todos estes benefícios nos teríamos outorgado. Cada um de nós seria, então, em resumo de todas as perfeições, uma espécie de Deus em miniatura.</p>
<p>Mas, afinal, que somos nós? Somos aquilo que queríamos ser? Não, incontestavelmente.</p>
<p>Na hipótese Deus, somos — visto que foi ele que nos criou — aquilo que ele quis que fôssemos. Deus é livre, não podia nos ter criado. Ou podia ter-nos criado menos perversos, porque é bom. Ou, então, podia ter-nos criado virtuosos, bem comportados, excelentes, enchendo-nos de todos os dotes físicos, intelectuais e morais, porque é todo poderoso.</p>
<p>Pela terceira vez: Que somos nós? Somos o que Deus quis que fôssemos, visto que ele criou-nos segundo o seu capricho e o seu gosto.</p>
<p>Se se admite que Deus existe e que foi ele que nos criou, não se pode dar outra resposta a pergunta “quem somos nós?”. Com efeito, foi Deus que nos deu os sentidos, as faculdades de compreensão, a sensibilidade, os meios de perceber, de sentir, de raciocinar, de agir. Ele previu, quis determinar as nossas condições de vida; coordenou as nossas necessidades, os nossos desejos, as nossas paixões, as nossas crenças, as nossas esperanças, os nossos ódios, as nossas ternuras, as nossas aspirações. Toda a máquina humana corresponde àquilo que ele quis. Ele arranjou e concebeu todas as peças do meio em que vivemos, preparando todas as circunstâncias que, a cada momento, dão um assalto a nossa vontade, determinando as nossas ações.</p>
<p>Perante este Deus formidavelmente armado, o homem é, portanto, irresponsável.</p>
<p>O que não está sob a dependência de ninguém é inteiramente livre; o que está um pouco sob dependência de um outro é um pouco escravo, e livre só para a diferença; o que está muito sob a dependência de um outro é muito escravo, e não é livre senão para o resto; enfim, o que esta em absoluto sob a dependência de outro, é totalmente escravo, não gozando de nenhuma liberdade.</p>
<p>Se Deus existe, é nesta última postura — a do escravo — que o homem se encontra em relação a Deus; e sua escravidão é tanto maior quanto maior for o espaço entre o Senhor e ele.</p>
<p>Se Deus existe, só ele é que sabe, pode, quer, só ele é livre. O homem nada sabe, nada pode, nada quer, a sua dependência é completa. Se Deus existe, ele é tudo — o homem, nada.</p>
<p>O homem, submetido a esta escravidão, aniquilado sob a dependência, plena e inteira de Deus, não pode ter nenhuma responsabilidade. E, se o homem é irresponsável, não pode ser julgado. Todo o julgamento implica um castigo ou uma recompensa; mas os atos de um irresponsável, não possuindo nenhum valor moral, estão isentos de qualquer responsabilidade. Os atos de um irresponsável podem ser úteis ou prejudiciais. Moralmente não são bons nem maus, como não são meritórios nem repreensíveis; julgados equitativamente, não podem ser recompensados nem castigados.</p>
<p>Portanto, Deus, erigindo-se em justiceiro, castigando e recompensando o homem irresponsável, não é mais do que um usurpador, que se arroga um direito arbitrário, usando dele contra toda a justiça.</p>
<p>Do que fica escrito, concluo:</p>
<p>a) Que a responsabilidade do mal moral é imputável a Deus, como igualmente lhe é imputável a responsabilidade do mal físico;</p>
<p>b) Que Deus é um juiz indigno, porque, sendo o homem irresponsável, não pode ser castigado nem recompensado.</p>
<h5 id="decimosegundo">12º argumento: Deus viola as regras fundamentais de equidade</h5>
<p>Admitamos por um instante que o homem é responsável, e veremos como, dentro desta hipótese, a justiça divina viola constantemente as regras mais elementares da equidade.</p>
<p>Se se admite que a prática de justiça não pode ser exercida sem uma sanção; que o magistrado tem, por mandato, fixá-la; e que há uma regra, segundo o qual o sentimento deve pronunciar-se unanimemente, é evidente que, da mesma forma, tem de haver uma escala de mérito e culpabilidade, assim como uma escala de recompensas e de castigos.</p>
<p>Admitindo este princípio, o magistrado que melhor pratica a justiça é aquele que proporciona o mais exatamente possível a recompensa ao mérito e o castigo a culpabilidade. E o magistrado ideal, impecável, perfeito, seria aquele que estabelece uma relação rigorosamente matemática entre o ato e a sanção.</p>
<p>Eu penso que esta regra elementar de justiça é acerta por todos. Pois bem, Deus, distribuindo o Céu e o Inferno, finge conhecer esta regra e viola-a. Qualquer que seja o mérito do homem, esse mérito é limitado (como o próprio homem); e, no entanto, a sanção da recompensa não o é: o Céu não tem limites, ainda que não seja senão pelo seu caráter de perpetuidade. Qualquer que seja a culpabilidade do homem, esta culpabilidade é limitada (como o próprio homem); e, no entanto, o castigo não o é: o Inferno o é: o Inferno é ilimitado, ainda que não seja senão pelo seu caráter de perpetuidade.</p>
<p>Há, pois, uma grande desproporção entre o mérito e a recompensa, entre a falta e a punição: o mérito e a falta são limitados, enquanto que a recompensa e o castigo são ilimitados.</p>
<p>Deus viola, pois, as regras fundamentais da equidade.</p>
<p>Finda aqui a minha tese. Resta-me apenas recapitulá-la e conclui-la.</p>
<h3>Recapitulação</h3>
<p>Prometi uma demonstração terminante, substancial, decisiva, da inexistência de Deus. Creio poder afirmar que cumpri esta promessa.</p>
<p>Não percais de vista que eu não me propus dar-vos um sistema do Universo que tornasse inútil todo o recurso à hipótese de uma Força sobrenatural, de uma Energia ou de uma Potência extramundial, de um Princípio superior ou anterior do Universo. Tive a lealdade, como era o meu dever, de vos dizer com toda a franqueza: apresentado assim, o problema não admite, dentro dos conhecimentos humanos, nenhuma solução definitiva; e que a única atitude que convém aos princípios refletidos e razoáveis é a expectativa.</p>
<p>O Deus que eu quis negar e do qual posso dizer que neguei a possibilidade é o Deus, é o Deus das religiões, o Deus Criador, Governador e Justiceiro, o Deus infinitamente sábio, poderoso, justo e bom, que os padres e os pastores se jactam de representar na Terra e que tentam impor a sua veneração.</p>
<p>Não há, não pode haver, equívoco. E este Deus que é preciso defender dos meus ataques.</p>
<p>Toda a discussão sobre outro terreno — e previno-vos disto, porque é necessário que vos ponhais em guarda contra as insídias do adversário — será apenas uma diversão, e, ainda mais: a prova provada de que o Deus das religiões não pode ser defendido nem justificado.</p>
<p>Provei que Deus, como criador, é inadmissível, imperfeito, inexplicável; estabeleci que Deus, como governador, é inútil, impotente, cruel, odioso, despótico; demonstrei que Deus, como justiceiro, é um magistrado indigno, pois que viola as regras essenciais da mais elementar equidade.</p>
<h3 id="conclusao">Conclusão</h3>
<p>Tal é, portanto, o Deus que, desde tempos imemoriais, nos tem ensinado e que ainda hoje se ensina às crianças, tanto nas escolas como nos lares. E que de crimes se tem cometido em nome dele! Que de ódios, guerras, calamidades tem sido furiosamente desencadeados pelos seus representantes! Esse Deus de tanto sofrimento não tem sido a causa! E quantos males provoca ainda hoje!</p>
<p>Há quantos séculos a religião traz a humanidade curvada sob a crença, espojada na superstição, prostrada resignadamente!</p>
<p>Não chegará jamais o dia em que, deixando de crer na justiça eterna, nas suas sentenças imaginárias, nas suas recompensas problemáticas, os seres humanos começam a trabalhar com um ardor infatigável pelo vento de uma justiça imediata, positiva e fraternal sobre a Terra? Não soará jamais a hora em que, desiludidos das consolações e das esperanças falazes que lhes sugere a crença de um paraíso compensador, os seres humanos comecem a fazer do nosso planeta do Éden de abundância, de paz e de liberdade, cujas portas estejam fraternalmente abertas para todos?</p>
<p>Há muito tempo que o contrato social é inspirado num Deus sem justiça, como há muito tempo que ele se inspira numa justiça sem Deus. Há muito tempo que as relações entre os países e os indivíduos dimanam num Deus sem filosofia, como há muito tempo que elas dimanam uma filosofia sem Deus. Há muitos séculos que monarcas, governos, castas, padres, condutores do povo e diretores de consciências, tratam a humanidade como um vil rebanho de cordeiros, para, em último lugar, serem esfolados, devorados, atirados ao matadouro.</p>
<p>Há séculos que os deserdados suportam passivamente a miséria e a servidão, graças ao milagre procedente do Céu e à visão horrorosa do inferno. É preciso acabar com este odioso sortilégio, com esta burla abominável.</p>
<p>Tu, leitor, que me lês, abre os olhos, examina, observa, compreende. O Céu de que te falam sem cessar; o Céu com a ajuda do qual procuram insensibilizar a tua miséria, anestesiar os teus sofrimentos e afogar os gemidos que, apesar de tudo, saem do teu peito, é um Céu irracional, um Céu deserto. Só o seu inferno é que é povoado, que é positivo.</p>
<p>Basta aos lamentos: os lamentos são vãos! Basta de prosternações: as prosternações são estéreis! Basta de preces: as preces são impotentes!</p>
<p>Levanta-te homem! E, direito, altivo, declara guerra implacável a Deus que, a tanto tempo, impõe aos teus irmãos e a ti próprio uma veneração embrutecedora!</p>
<p>Desembaraça-te deste tirano imaginário e sacode o jugo dos indivíduos que pretendem ser os representantes dele na Terra!</p>
<p>Mas, lembra-te bem, que, com este gesto de libertação, não terás cumprido senão uma das tarefas que te incumbe.</p>
<p>Não te esqueças de que de nada servirá quebrar as cadeias que os Deuses imaginários, celestes e eternos, tem forjado contra ti, se não quebrares igualmente as cadeias que, contra ti, tem forjado os Deuses passageiros da Terra.</p>
<p>Estes Deuses giram em torno de ti, procurando envilecer-te e degradar-te. Estes Deuses são homens como tu.</p>
<p>Ricos e governantes, estes Deuses da Terra tem-na povoado de inúmeras vítimas, de tormentos inexplicáveis.</p>
<p>Possam, enfim, um dia, os condenados da Terra insurgirem-se contra os seus verdugos, para fundarem uma Cidade na qual não possa haver destes monstros.</p>
<p>Quando te tiveres emancipado dos Deuses do Céu e da Terra, quando te tiveres desembaraçado dos chefes de cima e dos chefes debaixo, quando tiveres levado à pratica este duplo gesto de libertação, então, mas então somente, ó meu irmão, sairás do Inferno em que te encontras para entrar no Céu que tu realizarás! Deixarás as trevas da tua ignorância, para abraçar as puras claridades da tua inteligência, desperta, já, das influências letárgicas das religiões!</p>
<p id="autor">O Autor: Sebastien Faure nasceu no ano de 1858 na França. Criado em uma família burguesa e muito conservadora, recebeu ensino em um estabelecimento religioso. Os dirigentes do colégio, padres jesuítas, detectaram nele inteligência e vocação para seguir o “caminho de Deus”, e, aos dezessete anos entrou no noviciado. Foi um noviço exemplar. Por dezessete meses se aprofundou numa fé rigorosa e cega. Até que num dia recebeu um telegrama dizendo que seu pai estava gravemente doente. Visitou o seu pai, que disse-lhe que devia deixar a sua vida religiosa para sustentar a família. Seu pai morreu. Ele voltou a sua vida normal e, com o tempo, foi vendo a farsa em que ele estava acreditando. Se tornou ateu e anarquista, pelo qual lutou por quase toda a sua vida. Faleceu em 1942.</p>

</div>
<br><br><br><br>
</div>
</div>
</div>



<br><br><br><br>
<br><br><br><br>
<?php 
  include("../includes/footer.php"); 
?>